#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2025 Universitaet Heidelberg, ZITI

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../..)

APP = p2p_read_test

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk
